"
"" General
"
set nocompatible			" Enable vim features instead of strict vi compatibility
filetype off				" Required by Vundle

set rtp+=~/.vim/bundle/Vundle.vim 	" set the runtime path to include Vundle and initialize
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'christianrondeau/vim-base64'
Plugin 'fatih/vim-go'
Plugin 'hashivim/vim-terraform'
Plugin 'NLKNguyen/papercolor-theme'
Plugin 'VundleVim/Vundle.vim'
call vundle#end()            		" All of your Plugins must be added before the following line
filetype indent on			" Enable loading the indent file for specific file types

syntax on				" Enable syntax highlighting
filetype plugin on			" Enable plugins

filetype on				" Try to detect the filetype
syntax sync fromstart			" Sync syntax highlighting from the start of the file
set encoding=utf-8              	" The encoding displayed.
set fileencoding=utf-8          	" The encoding written to file.

set background=light			" PaperColor theme
colorscheme PaperColor

set mouse=a				" Enable the use of mouse in all modes.
set scrolloff=3				" Show 3 lines above or below cursor when scrolling
set ruler				" Enable the ruler
set showmatch				" Show matching brackets and parens
set number				"
set visualbell
set laststatus=2			" Displaying status line always

"
" Browsing files
"
let g:netrw_liststyle = 3		" Preferred view type
let g:netrw_banner = 0			" Removing the banner

"
" Finding files
"
set path+=**	      			" Search down into folders - Provides tab-completion for all file-related tasks
set wildmenu				" Use pop-up menu for tab completion of filenames

"
" Map jj to get to normal mode.
"
inoremap jj <ESC>

"
" Set <leader> key
"
let mapleader = ","
noremap \ ,

"
" Copy to and paste from the system clipboard (register +)
"
nnoremap <Leader>p "+p
nnoremap <Leader>P "+P
vnoremap <Leader>y "+y

"
" Split ctrl+hjkl navigation
"
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

"
"" Search
"
set ignorecase	      " Ignore case by default
set smartcase	      " Make search case sensitive only if it contains uppercase letters
set wrapscan	      " Search again from top when reached the bottom
set nohlsearch	      " Don't highlight after search

"
"" No backups
"
set nobackup
set nowritebackup
set noswapfile

autocmd BufNewFile,BufRead * setlocal formatoptions-=cro 	" Disable continuation of comments to the next line

"
"" Terraform configuration
"
let g:terraform_fmt_on_save=1

"
"" Golang configuration
"
